// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProcWatch.MonitorService.Data;

#nullable disable

namespace ProcWatch.MonitorService.Migrations
{
    [DbContext(typeof(ProcWatchDbContext))]
    [Migration("20251212163220_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("ProcWatch.MonitorService.Data.Entities.EventRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Endpoints")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("JsonPayload")
                        .HasColumnType("TEXT");

                    b.Property<string>("Op")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("Pid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProcessName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Path");

                    b.HasIndex("SessionId", "Timestamp");

                    b.HasIndex("SessionId", "Type");

                    b.ToTable("EventRecords");
                });

            modelBuilder.Entity("ProcWatch.MonitorService.Data.Entities.MonitoredSession", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ArgsJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IncludeChildren")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProcessName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("TargetPid")
                        .HasColumnType("INTEGER");

                    b.HasKey("SessionId");

                    b.HasIndex("StartTime");

                    b.ToTable("MonitoredSessions");
                });

            modelBuilder.Entity("ProcWatch.MonitorService.Data.Entities.ProcessInstance", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CommandLine")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentPid")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Pid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProcessName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "Pid");

                    b.ToTable("ProcessInstances");
                });

            modelBuilder.Entity("ProcWatch.MonitorService.Data.Entities.StatsSample", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("CpuPercent")
                        .HasColumnType("REAL");

                    b.Property<int>("HandleCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Pid")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PrivateBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProcessName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ThreadCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<long>("WorkingSetBytes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "Pid");

                    b.HasIndex("SessionId", "Timestamp");

                    b.ToTable("StatsSamples");
                });

            modelBuilder.Entity("ProcWatch.MonitorService.Data.Entities.EventRecord", b =>
                {
                    b.HasOne("ProcWatch.MonitorService.Data.Entities.MonitoredSession", "Session")
                        .WithMany("EventRecords")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("ProcWatch.MonitorService.Data.Entities.ProcessInstance", b =>
                {
                    b.HasOne("ProcWatch.MonitorService.Data.Entities.MonitoredSession", "Session")
                        .WithMany("ProcessInstances")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("ProcWatch.MonitorService.Data.Entities.StatsSample", b =>
                {
                    b.HasOne("ProcWatch.MonitorService.Data.Entities.MonitoredSession", "Session")
                        .WithMany("StatsSamples")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("ProcWatch.MonitorService.Data.Entities.MonitoredSession", b =>
                {
                    b.Navigation("EventRecords");

                    b.Navigation("ProcessInstances");

                    b.Navigation("StatsSamples");
                });
#pragma warning restore 612, 618
        }
    }
}
